## default connection pool
spring:
    datasource:
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5

        ## PostgreSQL
        url: jdbc:postgresql://localhost:5432/postgres
        username: carduser
        password: rasul123

    #drop n create table again, good for testing, comment this in production
    jpa:
        hibernate:
            ddl-auto: update
